/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package terminalterrestre;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

import clasesAuxiliares.AsientoAux;


public class Asiento10 extends javax.swing.JFrame {

    private Boleto boleto;
    long _idSalida;
    int _numAsientoModificado;
    List<AsientoAux> _asientosBD;
    Connection _conexion;
    List<JCheckBox> _asientos;

    public Asiento10(Boleto boleto, long idSalida, int numAsientoModificado) 
    {
        initComponents();
        _asientos = new ArrayList<JCheckBox>();
        _asientosBD = new ArrayList<AsientoAux>();
        this.boleto = boleto;
        this._idSalida = idSalida;
        this._numAsientoModificado = numAsientoModificado;
        llenaListaAsientos();
        llenaAsientosBD();
        cargaAsientos();
    }

    private void cargaAsientos() 
    {
        for (var asiento : _asientosBD)
        {
            if (asiento.getIdSalida() == _idSalida)
            {
                var a = _asientos.get(asiento.getNumAsiento() - 1);
                a.setEnabled(false);
            }
        }
        if (_numAsientoModificado > 0)
        {
            var a = _asientos.get(_numAsientoModificado - 1);
                a.setEnabled(true);
        }
    }

    private void llenaAsientosBD() 
    {
        _asientosBD.clear();
        
        String sentenciaSQL = "SELECT * FROM Ventas.Asiento";
        
        try
        {
            _conexion = ConexionSQL.getConnection(); 
            PreparedStatement statement = _conexion.prepareStatement(sentenciaSQL);
            ResultSet result = statement.executeQuery();
            
            while(result.next())
            {
                var nuevoAsiento = new AsientoAux();                
                nuevoAsiento.setIdAsiento(result.getLong("IdAsiento"));
                nuevoAsiento.setIdSalida(result.getLong("IdSalida"));
                nuevoAsiento.setDisponibilidad(result.getInt("Disponibilidad"));
                nuevoAsiento.setNumAsiento(result.getInt("NumAsiento"));                
                
                _asientosBD.add(nuevoAsiento); 
            }
        }
        catch(Exception ex)
        {
           JOptionPane.showMessageDialog(null, "Error al recuperar Asientos","Error", JOptionPane.ERROR_MESSAGE);            
        } 
    }

    private void llenaListaAsientos()
    {
        
        _asientos.add(chbAsiento1);
        _asientos.add(chbAsiento2);
        _asientos.add(chbAsiento3);
        _asientos.add(chbAsiento4);
        _asientos.add(chbAsiento5);
        _asientos.add(chbAsiento6);
        _asientos.add(chbAsiento7);
        _asientos.add(chbAsiento8);
        _asientos.add(chbAsiento9);
        _asientos.add(chbAsiento10);
    }

    private String recuperaAsiento()
    {
        if (chbAsiento1.isSelected()) 
            return chbAsiento1.getText();
        if (chbAsiento1.isSelected())            
            return chbAsiento1.getText();
        if (chbAsiento2.isSelected())
            return chbAsiento2.getText();
        if (chbAsiento3.isSelected())
            return chbAsiento3.getText();
        if (chbAsiento4.isSelected())
            return chbAsiento4.getText();
        if (chbAsiento5.isSelected())
            return chbAsiento5.getText();
        if (chbAsiento6.isSelected())
            return chbAsiento6.getText();
        if (chbAsiento7.isSelected())
            return chbAsiento7.getText();
        if (chbAsiento8.isSelected())
            return chbAsiento8.getText();
        if (chbAsiento9.isSelected())
            return chbAsiento9.getText();
        if (chbAsiento10.isSelected()) 
            return chbAsiento10.getText();
        
        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReservar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        chbAsiento1 = new javax.swing.JCheckBox();
        chbAsiento2 = new javax.swing.JCheckBox();
        chbAsiento3 = new javax.swing.JCheckBox();
        chbAsiento4 = new javax.swing.JCheckBox();
        chbAsiento5 = new javax.swing.JCheckBox();
        chbAsiento6 = new javax.swing.JCheckBox();
        chbAsiento7 = new javax.swing.JCheckBox();
        chbAsiento8 = new javax.swing.JCheckBox();
        chbAsiento9 = new javax.swing.JCheckBox();
        chbAsiento10 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asiento");
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnReservar.setText("Reservar ");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccione su Asiento ");

        chbAsiento1.setText("Asiento 1");

        chbAsiento2.setText("Asiento 2");

        chbAsiento3.setText("Asiento 3");

        chbAsiento4.setText("Asiento 4");

        chbAsiento5.setText("Asiento 5");

        chbAsiento6.setText("Asiento 6");

        chbAsiento7.setText("Asiento 7");

        chbAsiento8.setText("Asiento 8");

        chbAsiento9.setText("Asiento 9");

        chbAsiento10.setText("Asiento 10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbAsiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbAsiento2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbAsiento3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbAsiento5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbAsiento7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbAsiento9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbAsiento4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReservar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chbAsiento6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chbAsiento8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chbAsiento10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbAsiento1)
                    .addComponent(chbAsiento3)
                    .addComponent(chbAsiento5)
                    .addComponent(chbAsiento7)
                    .addComponent(chbAsiento9))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbAsiento2)
                    .addComponent(chbAsiento4)
                    .addComponent(chbAsiento6)
                    .addComponent(chbAsiento8)
                    .addComponent(chbAsiento10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnReservar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) 
    {
        boleto.asientoCerrado();
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) 
    {
        boleto.asientoCerrado();
    }

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt)
    {
        var asiento = recuperaAsiento();
        var numAsiento = asiento.split(" ");
        var _numAsiento = Integer.parseInt(numAsiento[1]);
        boleto.setNumAsiento(_numAsiento);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asiento10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asiento10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asiento10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asiento10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asiento10(new Boleto(""), 0,0 ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReservar;
    private javax.swing.JCheckBox chbAsiento1;
    private javax.swing.JCheckBox chbAsiento10;
    private javax.swing.JCheckBox chbAsiento2;
    private javax.swing.JCheckBox chbAsiento3;
    private javax.swing.JCheckBox chbAsiento4;
    private javax.swing.JCheckBox chbAsiento5;
    private javax.swing.JCheckBox chbAsiento6;
    private javax.swing.JCheckBox chbAsiento7;
    private javax.swing.JCheckBox chbAsiento8;
    private javax.swing.JCheckBox chbAsiento9;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
