/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package terminalterrestre;

import java.util.HashMap;
import java.util.Map;
import terminalterrestre.Boleto;

/**
 *
 * @author TorresJ2
 */
public class PanelControl extends javax.swing.JFrame {
public Map<String, Boleto> formulariosAbiertos = new HashMap<>();
    /**
     * Creates new form PanelControl
     */
    String USUARIO;
    public PanelControl(String USUARIO) {
        initComponents();
        this.USUARIO = USUARIO;
        seteaPanel();
    }

    private void seteaPanel() 
    {
        if (USUARIO.equals("Vendedor"))
        {
           btnCiudad.setEnabled(false);
           btnEstacion.setEnabled(false);
           btnTerminal.setEnabled(false);
           btnOperador.setEnabled(false);
           btnPasjero.setEnabled(false);
           btnCliente.setEnabled(false);
           btnTarjeta.setEnabled(false);
           btnTransporte.setEnabled(false);
        }
        if (USUARIO.equals("Customer Service"))
        {
           btnCiudad.setEnabled(false);
           btnEstacion.setEnabled(false);
           btnTerminal.setEnabled(false);
           btnOperador.setEnabled(false);
           btnPasjero.setEnabled(false);
           btnItinerario.setEnabled(false);
           btnTransaccion.setEnabled(false);
           btnTransporte.setEnabled(false);
           btnBoleto.setEnabled(false);
           btnSalida.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnCiudad = new javax.swing.JButton();
        btnOperador = new javax.swing.JButton();
        btnEstacion = new javax.swing.JButton();
        btnTerminal = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnTarjeta = new javax.swing.JButton();
        btnItinerario = new javax.swing.JButton();
        btnPasjero = new javax.swing.JButton();
        btnTransporte = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        btnTransaccion = new javax.swing.JButton();
        btnBoleto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de Control");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccione la opción deseada ");

        btnCiudad.setText("Ciudad");
        btnCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiudadActionPerformed(evt);
            }
        });

        btnOperador.setText("Operador");
        btnOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperadorActionPerformed(evt);
            }
        });

        btnEstacion.setText("Estación");
        btnEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstacionActionPerformed(evt);
            }
        });

        btnTerminal.setText("Terminal");
        btnTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminalActionPerformed(evt);
            }
        });

        btnCliente.setText("Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnTarjeta.setText("Tarjeta Cliente");
        btnTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetaActionPerformed(evt);
            }
        });

        btnItinerario.setText("Itinerario");
        btnItinerario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItinerarioActionPerformed(evt);
            }
        });

        btnPasjero.setText("Pasajero");
        btnPasjero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasjeroActionPerformed(evt);
            }
        });

        btnTransporte.setText("Transporte");
        btnTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransporteActionPerformed(evt);
            }
        });

        btnSalida.setText("Salida");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        btnTransaccion.setText("Transacción");
        btnTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaccionActionPerformed(evt);
            }
        });

        btnBoleto.setText("Boleto");
        btnBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTerminal)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCiudad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTransaccion)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnOperador)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnCliente)
                                        .addGap(31, 31, 31))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPasjero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTarjeta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTransporte)
                                    .addComponent(btnItinerario))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSalida)
                                    .addComponent(btnBoleto, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addComponent(btnEstacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCiudad)
                    .addComponent(btnOperador)
                    .addComponent(btnItinerario)
                    .addComponent(btnSalida)
                    .addComponent(btnCliente))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstacion)
                    .addComponent(btnPasjero)
                    .addComponent(btnTransporte)
                    .addComponent(btnBoleto)
                    .addComponent(btnTarjeta))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTerminal)
                    .addComponent(btnTransaccion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiudadActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ciudad().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnCiudadActionPerformed

    private void btnEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstacionActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estacion().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnEstacionActionPerformed

    private void btnOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperadorActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operador().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnOperadorActionPerformed

    private void btnTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminalActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Terminal().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnTerminalActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetaActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TarjetaCliente().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnTarjetaActionPerformed

    private void btnItinerarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItinerarioActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Itinerario(USUARIO).setVisible(true);
            }
        });
    }//GEN-LAST:event_btnItinerarioActionPerformed

    private void btnPasjeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasjeroActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pasajero().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnPasjeroActionPerformed

    private void btnTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransporteActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transporte().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnTransporteActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salida(USUARIO).setVisible(true);
            }
        });
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaccionActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaccion(USUARIO).setVisible(true);
            }
        });
    }//GEN-LAST:event_btnTransaccionActionPerformed

    private void btnBoletoActionPerformed(java.awt.event.ActionEvent evt) 
    {
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boleto(USUARIO).setVisible(true);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelControl("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoleto;
    private javax.swing.JButton btnCiudad;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEstacion;
    private javax.swing.JButton btnItinerario;
    private javax.swing.JButton btnOperador;
    private javax.swing.JButton btnPasjero;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton btnTarjeta;
    private javax.swing.JButton btnTerminal;
    private javax.swing.JButton btnTransaccion;
    private javax.swing.JButton btnTransporte;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
